#cloud-config
users: # Benutzerkonfiguration
  - name: ubuntu # Benutzername ist "ubuntu"
    sudo: ALL=(ALL) NOPASSWD:ALL # sudo-Regeln für diesen Benutzer
    groups: users, admin # Der Benutzer gehört zu den Gruppen "users" und "admin"
    home: /home/ubuntu # Das Heimatverzeichnis des Benutzers ist "/home/ubuntu"
    shell: /bin/bash # Der Benutzer verwendet die Bash-Shell
    ssh_authorized_keys: # Autorisierte SSH-Schlüssel
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCb2pO/WZ7yHpLBCc5M9qx1bc/lTV+JjzqA0TO+Aq3IcX4HvE5y6TWh/RaxGMcVzmfSpQ2PrJn97EQ0AdMU5TmHj8SAUhvmie3vzK3y8TS0vcZGdLTemv7jn5HHhUmYQlR2QAWG/nSrzdlgPj/zBtSHrvNudNFqQ3PEYiq6IUMT45+XIgOZb2hXFbxXzg/W4xwpEpP58YT/2Pbhh2dOSnNxZZQ/hEZS3GmNlNQzIM8iF8qc1pPGiN+bRbo5DjGUu+VBmwCHvLM/iANfxtBVZelIDcsgxL1w4dIxmegSlcmG+idNdYOkRKyWf/tEBXH01kzv2PJ1lP28z5fqgdROFzG9 aws-key
ssh_pwauth: false # SSH-Passwortauthentifizierung ist deaktiviert
disable_root: false # Das Anmelden als Root-Benutzer ist aktiviert
package_update: true # Die Paketliste wird beim Starten der Instanz aktualisiert
packages: # Installierte Pakete
  - curl # Installiert das Paket "curl"
  - wget # Installiert das Paket "wget"
