#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCz/wpWmsCxaQyuNFrIachc/q9nUdByoUcBcicl/wnKLFktKp6du9np9Uhmo4M0tVHNnWCt5uNEi2ks/0XEbg2J+4heuAAKEDr/TVbgabiWGclYKpEWZvmw8gsQwfpAKVG4aS2re7wB2uhw82ZqzJVpGm3ne+sNnz5uVrxN8HUnuR2OWJD6bA9l/fBmE6zdObVXgrCJGjZmVyB5GMeTDJKExgoBpLggZn9CNdu7Sx989xtNLehu6SWM+mGCq9Lcu7usiPG+SuEb8XynYaCOnv8+Oko6SYeJ9Omq/E7Eg6vZHqCbBQ81TIZrGKcikLmF2xP7EOprGOSPVewke7ak7vvmOI+p/RfIAyXj1+GYny+esk9G+qDRFXP9uiIlMfH1oGkQkztvSDMH+EOHqgY66NWQJPj83CaWH/euR0MROHXjm1ar3RuN9qcASAnzCOQQ1FMwFkpIV5x0NDRx0Zp1rLt8ZUFykmIuHZI4g9u6RdAiuWUxx9/eF0fXZa6Ju7GEMKeMtZxJJjmB/WCOylbkT+NPw5RcxgyRLKmUAicnYKXBmULY3pQM/Ui8KiCyJqRbLDBAR+XZYsZ7X5uhcuteu8KIfA2xEbInB4Q3c0DnnSih+GEC4pEbz+NOfeCpLJEn4gfyV1S9S08sG62ls8NPFociA9aWmE1oXfcqwvOkkYhxOw== aws-key
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCb2pO/WZ7yHpLBCc5M9qx1bc/lTV+JjzqA0TO+Aq3IcX4HvE5y6TWh/RaxGMcVzmfSpQ2PrJn97EQ0AdMU5TmHj8SAUhvmie3vzK3y8TS0vcZGdLTemv7jn5HHhUmYQlR2QAWG/nSrzdlgPj/zBtSHrvNudNFqQ3PEYiq6IUMT45+XIgOZb2hXFbxXzg/W4xwpEpP58YT/2Pbhh2dOSnNxZZQ/hEZS3GmNlNQzIM8iF8qc1pPGiN+bRbo5DjGUu+VBmwCHvLM/iANfxtBVZelIDcsgxL1w4dIxmegSlcmG+idNdYOkRKyWf/tEBXH01kzv2PJ1lP28z5fqgdROFzG9 aws-key
ssh_pwauth: false

disable_root: false

package_update: true

packages:
  - apache2
  - libapache2-mod-php

write_files:
  - path: /var/www/html/image.php
    content: |
      <?php
      $ihrname = "Noris Girolimetto";
      $bildquelle = ""C:\Users\noris\OneDrive\Bilder\Screenshots\fran.png"";
      ?>

      <html>
        <head>
          <title><?php echo($ihrname); ?></title>
        </head>
        <body>
          Das ist der Fran mit mir FaceTime.
          <br />
          <img src="https://norisgiro.s3.us-east-1.amazonaws.com/fran.png?response-content-disposition=inline&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEBwaDGV1LWNlbnRyYWwtMSJHMEUCIHSN9t%2FLnIi%2FUGZeoZVsJFFiiRooQq2zs4782DIlPkPlAiEA9iHT2HsURIAaja2owcq1fpPHJZgYdpiQy4755HHopw4q%2FQIIFhAAGgw3ODE3NDcwODQ2MDMiDAmMysFZOrAGJdAt4SraAuCVwXzMID7NFse29n12ZZEql639LPYvckaFCnNc%2Fjhhn8NNwuzOAvpFvacxQ2V1t8SUztQBOvfYHwnliiCmnOd%2BmsBC7PolpzjuFeJnToUvNOl3fqIGeY%2BRV8RDyVuXu7106Rg9RfpLvG413Z5yO4E61tnAS3ZPvCbPN%2BFurO%2BFB4B2uIBe3poRU9PxNFxImE4JmxA%2FiZiKaaRmByWsCvr3bhxBk3ztlFww2h9DbBUO%2Fsx6a0U2EDRIUpc2aBRHAoBSKsLz%2Bpui%2BMGA0Z1HNeq5%2BWN%2F0w9Guaw9UUBkKn%2FYMR%2BrVNA7pcfSobBRm%2BZ%2BnAxKCNzGy88uJh7LR%2B5RY5SCdQ3Qntx69bG9FPiBPtvc809Hf%2BSrDM2JvuHt83LxvEwxQ40NCpS6oRo8wsfllVGw%2F2g%2FtE7G7MMDLi7xjeDlhmLdpIl38ZUKVwmcSacrtc1RxZsujIPMqUcw5O61qAY6hwLtF8LHhNC%2FEzmv5IlQEGP2ZKFnTykB5cTuZ3G6KrD4XadGvuh%2FyL4jps5rneJwIwYoB27KckztLLhT%2FSyJl8XlQeomTpYGgiJ1%2FtB%2B6nhgzQbpGOq2vChUiz4b6JHm3crSBHWk5x%2Bs88SaAJpHq0ugQFxKbJZlsjlFf8PM%2FYtmXkicrwgbvoNGhhb4qHQq37w2nCSoXo8%2F7M3Q8kIGS2qbBki1YEGlQhu7nIMY31t3f4FUOnZTgdQ33GBM0oLvl0Z%2BdZnd3cgQA5SJhEx8a3SaUh1qjyrucCMNJ3YYrkjfs5Wznb22viyN6o%2F3DxDk7ln6Nkt65%2FoQfqcMC0EnAqaURjz4gGsx1g%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20230922T131752Z&X-Amz-SignedHeaders=host&X-Amz-Expires=300&X-Amz-Credential=ASIA3MA6B3U54ZRGEJWX%2F20230922%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=cb681d7b78c31235bcbde829d68d05f230fe92bb068eb7f790ee214a576fc744" />
          <p>Dieses Bild kommt aus meinem "Bilder" Ordner.</p>
        </body>
      </html>

runcmd:
  - sudo systemctl restart apache2
