#cloud-config
users: # benutzerkonfiguration für neues system
  - name: ubuntu # benutzername
    sudo: ALL=(ALL) NOPASSWD:ALL #unbeschränkter Zugriff
    groups: users, admin # gruppen zuteilung
    home: /home/ubuntu # heimatsverzeichnis
    shell: /bin/bash # standard shell
    ssh_authorized_keys:
      - ssh rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCU+4Z/KkAWTig66Mwh+u2h9t3QbnNli7w5LPeXKqZFmW7wWwb97nt0wNw/A7UHzi5xkVmrp9Yk7pZf5IDV6mRKOlrcWA4pD4mC0Bwx1FUb4sGT3jRw3M3HBymIRioQM23C5x2/0cSM+c6xR1EAnS8zbvxapInZk2o3+YsPT6O+X45+m9Hepewtc3Fqg0qqxvkUbQueEBkojowFiVdml2Lj1r9Vijt+Ekd+5P7yqITB7UiBPa/fx3OlIdDZwFkvSDuA8wqFkQ0tS6N4mWKMghaaF1UoxzjvX8Ql77A2AnbQL/TBwXUIHiwTOkJ5BpPiIfWfUWwPRDxQuAx9AMeiro8n aws-key   
       - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCb2pO/WZ7yHpLBCc5M9qx1bc/lTV+JjzqA0TO+Aq3IcX4HvE5y6TWh/RaxGMcVzmfSpQ2PrJn97EQ0AdMU5TmHj8SAUhvmie3vzK3y8TS0vcZGdLTemv7jn5HHhUmYQlR2QAWG/nSrzdlgPj/zBtSHrvNudNFqQ3PEYiq6IUMT45+XIgOZb2hXFbxXzg/W4xwpEpP58YT/2Pbhh2dOSnNxZZQ/hEZS3GmNlNQzIM8iF8qc1pPGiN+bRbo5DjGUu+VBmwCHvLM/iANfxtBVZelIDcsgxL1w4dIxmegSlcmG+idNdYOkRKyWf/tEBXH01kzv2PJ1lP28z5fqgdROFzG9 aws-key
ssh_pwauth: false
disable_root: false
package_update: true
packages:
  - curl 
  - wget 
  - mariadb-server
  - php-mysqli
  
runcmd:
- sudo apt update
- sudo apt -y install mariadb-server php-mysqli
- sudo mysql -sfu root -e "GRANT ALL ON *.* TO 'admin'@'%' IDENTIFIED BY 'password' WITH GRANT OPTION;"
- sudo systemctl restart mariadb.service
- sudo a2enconf adminer
- sudo sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mysql/mariadb.conf.d/50-server.cnf
- sudo systemctl restart mysql